name: Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r docs/requirements.txt
      - name: Test documentation
        run: |
          make -C docs doctest
      - name: Sphinx build
        run: |
          sphinx-build docs docs/_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
